/**
 * Curated demo tutors.
 *
 * Field names mirror the live API document shape so that swapping in the real
 * backend later is a change of import, not a change of component code:
 *   _id, tutorName, subject, image, availability, hourlyFee, totalSlot,
 *   startDate, teachingMode, district, address, institution, experienceYears
 *
 * Plus two fields the live API is missing but `my-tutors` depends on:
 *   tutorEmail, addedBy
 *
 * Values reproduce `code.html` section 5 exactly.
 */

/** Shared demo owner, so `my-tutors` has something real to render. */
export const DEMO_OWNER = {
  name: "Sayeed Kabir",
  email: "sayeed@mediqueue.app",
  id: "demo-user-kabir",
};

export const DEMO_TUTORS = [
  {
    _id: "demo-tutor-001",
    tutorName: "Dr. Ariful Islam",
    subject: "Physiology",
    institution: "Dhaka Medical College",
    teachingMode: "Online",
    availability: "Mon, Wed - 7PM",
    hourlyFee: 1200,
    totalSlot: 0,
    startDate: "2026-05-22",
    experienceYears: 6,
    district: "Dhaka",
    address: "Green Road, Dhanmondi",
    image: "/images/tutors/ariful-islam.jpg",
    tutorEmail: "ariful.islam@mediqueue.app",
    addedBy: DEMO_OWNER.email,
  },
  {
    _id: "demo-tutor-002",
    tutorName: "Dr. Nusrat Jahan",
    subject: "Anatomy",
    institution: "Chittagong Medical College",
    teachingMode: "Both",
    availability: "Sat, Tue - 5PM",
    hourlyFee: 1500,
    totalSlot: 0,
    startDate: "2026-05-25",
    experienceYears: 4,
    district: "Chattogram",
    address: "Chawkbazar, IPC Area",
    image: "/images/tutors/nusrat-jahan.jpg",
    tutorEmail: "nusrat.jahan@mediqueue.app",
    addedBy: DEMO_OWNER.email,
  },
  {
    _id: "demo-tutor-003",
    tutorName: "Tahsin Ahmed",
    subject: "Biochemistry",
    institution: "Sylhet MAG Osmani Medical College",
    teachingMode: "Online",
    availability: "Sun, Thu - 6PM",
    hourlyFee: 1000,
    totalSlot: 3,
    startDate: "2026-05-24",
    experienceYears: 2,
    district: "Sylhet",
    address: "Subidbazar",
    image: "/images/tutors/tahsin-ahmed.jpg",
    tutorEmail: "tahsin.ahmed@mediqueue.app",
    addedBy: DEMO_OWNER.email,
  },
  {
    _id: "demo-tutor-004",
    tutorName: "Dr. Sajid Hasan",
    subject: "Pathology",
    institution: "Rajshahi Medical College",
    teachingMode: "Offline",
    availability: "Fri, Sat - 9AM",
    hourlyFee: 1800,
    totalSlot: 1,
    startDate: "2026-05-23",
    experienceYears: 5,
    district: "Rajshahi",
    address: "Kazihata, Medical Road",
    image: "/images/tutors/sajid-hasan.jpg",
    tutorEmail: "sajid.hasan@mediqueue.app",
    addedBy: DEMO_OWNER.email,
  },
  {
    _id: "demo-tutor-005",
    tutorName: "Dr. Fariha Zaman",
    subject: "General Medicine",
    institution: "Sir Salimullah Medical College",
    teachingMode: "Online",
    availability: "Everyday - 8PM",
    hourlyFee: 2000,
    totalSlot: 2,
    startDate: "2026-06-01",
    experienceYears: 7,
    district: "Dhaka",
    address: "Sector 4, Uttara",
    image: "/images/tutors/fariha-zaman.jpg",
    tutorEmail: "fariha.zaman@mediqueue.app",
    addedBy: DEMO_OWNER.email,
  },
  {
    _id: "demo-tutor-006",
    tutorName: "Dr. Asif Iqbal",
    subject: "Anatomy",
    institution: "Mymensingh Medical College",
    teachingMode: "Both",
    availability: "Tue, Thu - 4PM",
    hourlyFee: 1100,
    totalSlot: 4,
    startDate: "2026-05-26",
    experienceYears: 3,
    district: "Mymensingh",
    address: "Charpara",
    image: "/images/tutors/asif-iqbal.jpg",
    tutorEmail: "asif.iqbal@mediqueue.app",
    addedBy: DEMO_OWNER.email,
  },
];

/**
 * Second batch, used by `/tutors` so the browse page is not a copy of the home grid.
 * Same shape, different subjects and colleges so filters have something to bite on.
 */
export const DEMO_TUTORS_EXTENDED = [
  {
    _id: "demo-tutor-007",
    tutorName: "Dr. Nusrat Jahan",
    subject: "Pharmacology",
    institution: "Chittagong Medical College",
    teachingMode: "Online",
    availability: "Wed - 6PM",
    hourlyFee: 1300,
    totalSlot: 2,
    startDate: "2026-05-27",
    experienceYears: 3,
    district: "Chattogram",
    address: "Chawkbazar, IPC Area",
    image: "/images/tutors/nusrat-jahan.jpg",
    tutorEmail: "nusrat.jahan@mediqueue.app",
    addedBy: "other.owner@mediqueue.app",
  },
  {
    _id: "demo-tutor-008",
    tutorName: "Dr. Rafiq Mahmud",
    subject: "Pathology",
    institution: "Dhaka Medical College",
    teachingMode: "Both",
    availability: "Sat, Sun - 10AM",
    hourlyFee: 1600,
    totalSlot: 5,
    startDate: "2026-05-29",
    experienceYears: 8,
    district: "Dhaka",
    address: "Mohammadpur, Dhaka",
    image: "/images/tutors/rafiq-mahmud.jpg",
    tutorEmail: "rafiq.mahmud@mediqueue.app",
    addedBy: "other.owner@mediqueue.app",
  },
  {
    _id: "demo-tutor-009",
    tutorName: "Dr. Sabrina Haque",
    subject: "Physiology",
    institution: "Khulna Medical College",
    teachingMode: "Offline",
    availability: "Fri - 4PM",
    hourlyFee: 950,
    totalSlot: 3,
    startDate: "2026-05-30",
    experienceYears: 2,
    district: "Khulna",
    address: "Boyra, Khulna",
    image: "/images/tutors/sabrina-haque.jpg",
    tutorEmail: "sabrina.haque@mediqueue.app",
    addedBy: "other.owner@mediqueue.app",
  },
  {
    _id: "demo-tutor-010",
    tutorName: "Dr. Imran Chowdhury",
    subject: "General Medicine",
    institution: "Rangpur Medical College",
    teachingMode: "Online",
    availability: "Mon, Thu - 9PM",
    hourlyFee: 2100,
    totalSlot: 1,
    startDate: "2026-06-02",
    experienceYears: 9,
    district: "Rangpur",
    address: "Station Road, Rangpur",
    image: "/images/tutors/imran-chowdhury.jpg",
    tutorEmail: "imran.chowdhury@mediqueue.app",
    addedBy: "other.owner@mediqueue.app",
  },
];
